### ISSUE TITLE
v2023.40.2 Error

### ISSUE THREAD

**Issue by wabass** [REMnux/salt-states#262]
```
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 100, in <module>
    check_compatibility(urllib3.__version__, chardet_version, charset_normalizer_version)
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 85, in check_compatibility
    raise Exception("You need either charset_normalizer or chardet installed")
Exception: You need either charset_normalizer or chardet installed

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by wabass** [comment]
![image](https://github.com/REMnux/salt-states/assets/109649776/6e6c690f-c84c-4eaa-9fcd-6427d587a19f)

**Comment by digitalsleuth** [comment]
Hi @wabass , we're currently using Salt 3006 in the remnux-cli. To upgrade your remnux installation, simply download the latest [remnux-cli](https://github.com/remnux/remnux-cli/releases/latest) and follow the instructions to install and execute.

Cheers!

**Comment by digitalsleuth** [comment]
@lennyzeltser I believe we can close this issue.
