### ISSUE TITLE
FakeNet-NG package is broken for python2, python3

### ISSUE THREAD

**Issue by thejoelpatrol** [REMnux/salt-states#282]
**Appliance version:** remnux-v7-focal-virtualbox.ova
**OVA hash**: 412689aabf7d203c3fb46d141704671a1dbf858b13b404f0bbd0096f6d6bd7b9
**lsb_release**: Ubuntu 20.04.4 LTS
**Package**: fakenet-ng.sls
**FakeNet version**: 3.1

We have run  `remnux upgrade` as of 2024-04-10.
 
There are two issues with the installation of FakeNet. Out of the box, this error occurs:

```
remnux@remnux:~$ sudo fakenet
Traceback (most recent call last):
  File "/usr/local/bin/fakenet", line 5, in <module>
    from fakenet.fakenet import main
  File "/usr/local/lib/python2.7/dist-packages/fakenet/fakenet.py", line 23, in <module>
    from configparser import ConfigParser
ImportError: No module named configparser
```
It seems that currently FakeNet is installed as a python2 package. The ConfigParser package appears to be missing for python2, most immediately leading to this error.

But more importantly, FakeNet 3.1 now only supports Python 3.7 or higher.  It should be installed for python3, not python2.

**Comment by digitalsleuth** [comment]
Hi @thejoelpatrol I've taken a look at this, and unfortunately the latest version of Fakenet (which is a Python3 update) is still in its Alpha / Pre-release phase. There is currently no version 3.1 available, and the only Python 3 versions available are 3.0-alpha and 3.2-alpha which appear to still have some bugs. 

I'll keep looking into what can be done to mitigate these errors, and keep this Issue updated.

**Comment by tinajohnson** [comment]
Hi @digitalsleuth,
Thank you for your comment clarifying what is required from FakeNet to resolve this issue. FakeNet team will look into this.

**Comment by tinajohnson** [comment]
@digitalsleuth We just released FakeNet 3.3. Hopefully, this helps in including the Python 3 version of FakeNet in REMnux.

**Comment by digitalsleuth** [comment]
Thanks @tinajohnson , I'll take a peek!

**Comment by tinajohnson** [comment]
Thank you, I now understand that this is the error you referenced in your earlier message. I will work on this.

**Comment by digitalsleuth** [comment]
Hi @tinajohnson , I actually submitted a PR for the resolution just before you replied. It's the resolution provided by @thejoelpatrol in the reference issue.

**Comment by tinajohnson** [comment]
Hi @digitalsleuth,
We have a new fakenet [release](https://github.com/mandiant/flare-fakenet-ng/releases/tag/v3.5) with the error fixes we talked about earlier. Hope this helps in getting the python 3 fakenet into REMnux. Let me know if I can be of any assistance.

**Comment by digitalsleuth** [comment]
Hi @tinajohnson , this is great! Let me take a run at it to make sure it's all good, then I'll see about getting it added!

**Comment by thejoelpatrol** [comment]
Glad to see the progress here! Thanks @tinajohnson @digitalsleuth. This will be a big help for me once it's updated. @digitalsleuth do you have any rough idea when this might be included?

**Comment by digitalsleuth** [comment]
Hi @thejoelpatrol , I expect in the next couple of days. I'm just testing out the states for 20.04 and 24.04 right now to prepare for upcoming support. You should see a PR soon!

**Comment by digitalsleuth** [comment]
@thejoelpatrol , the PR has been submitted, testing is successful in both Focal and Noble.

**Comment by tinajohnson** [comment]
Thank you @thejoelpatrol!
