### ISSUE TITLE
Signatures are missing for the v2024.21.4 release

### ISSUE THREAD

**Issue by seanthegeek** [REMnux/salt-states#287]
` remnux-salt-states-v2024.21.4.tar.gz.asc` and ` remnux-salt-states-v2024.21.4.sha256.asc` are missing from the v2024.21.4 release, causing installation to fail. @lennyzeltser

```
> remnux-cli@1.3.9.1.g849ae31
> remnux-version: v2024.18.1

> downloading v2024.21.4
>> downloading remnux-salt-states-v2024.21.4.tar.gz.asc
>> downloading remnux-salt-states-v2024.21.4.tar.gz.sha256
>> downloading remnux-salt-states-v2024.21.4.tar.gz.sha256.asc
/snapshot/remnux-cli/remnux-cli.js:362
          throw new Error(res.body)
          ^

Error
    at Request.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:362:17)
    at Request.emit (events.js:315:20)
    at Request.onRequestResponse (/snapshot/remnux-cli/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by lennyzeltser** [comment]
Oops! Just issued v2024.21.5. Could you please try it?

**Comment by seanthegeek** [comment]
That worked. Thanks.
